load("@io_bazel_rules_go//go:def.bzl", "go_prefix", "go_binary")

go_prefix("github.com/bazelbuild/rules_go/tests/custom_go_toolchain")

go_binary(
    name = "print_version",
    srcs = ["print_version.go"],
    tags = ["manual"],
)
