package(default_visibility = ["//examples/monobuild/cmd:__pkg__"])

load("//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "lib2.go",
    ],
    importpath = "totally/different/import/for/lib2",
)
