load("//proto:go_proto_library.bzl", "go_proto_library")

go_proto_library(
    name = "useful_proto",
    srcs = ["useful.proto"],
    visibility = ["//visibility:public"],
    deps = ["@com_github_golang_protobuf//ptypes/duration:go_default_library"],
)
