package(
    default_visibility = ["//visibility:public"],
)

alias(
    name = "toolchain",
    actual = "@io_bazel_rules_go_toolchain//:toolchain",
)

alias(
    name = "go_tool",
    actual = "@io_bazel_rules_go_toolchain//:go_tool",
)

alias(
    name = "go_include",
    actual = "@io_bazel_rules_go_toolchain//:go_include",
)

alias(
    name = "go_root",
    actual = "@io_bazel_rules_go_toolchain//:go_root",
)
