load("@io_bazel_rules_go//go/private:go_tool_binary.bzl", "go_tool_binary")

go_tool_binary(
    name = "asm",
    srcs = [
        "asm.go",
        "filter.go",
    ],
    visibility = ["//visibility:public"],
)
