package(default_visibility = ["//examples/lib:__pkg__"])

load("//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "doc.go",
        "thought.go",
    ],
)
