load("@io_bazel_rules_go//go:def.bzl", "go_prefix", "go_test")

go_prefix("github.com/bazelbuild/rules_go")

go_test(
    name = "go_default_test",
    size = "small",
    srcs = ["test_filter_test.go"],
    tags = ["manual"],
)
