package(default_visibility = ["//visibility:public"])

load("//go/private:go_tool_binary.bzl", "go_tool_binary")

# This binary is used implicitly by go_test().
go_tool_binary(
    name = "generate_test_main",
    srcs = ["generate_test_main.go"],
)
